name: Android CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 7 * * *"

jobs:
  lint-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle-task: [lint, build]
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run gradle tasks
        run: ./gradlew ${{ matrix.gradle.task }}
